version: '3'

x-common-variables: &common-variables
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  CELERY_BACKEND_URL: 'redis://redis:6379/1'
  TASK_SYNC_URL: 'redis://redis:6379/2'
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
  BACKEND_FOLDER_PATH: ${PWD}/backend
  SYNC_FILE_SERVER_STORE_PATH: ${SYNC_FILE_SERVER_STORE_PATH}

services:
  frontend:
    build: 
      context: ./frontend/
      dockerfile: frontend.Dockerfile
    container_name: gait-anywhere-frontend
    ports:
      - 47000:80
    depends_on:
      - backend
      - file_server
    networks:
      - gait_anywhere_network

  backend:
    image: gait-anywhere-backend:latest
    build:
      context: ./backend/
      dockerfile: backend.Dockerfile
    container_name: gait-anywhere-backend
    environment:
      <<: *common-variables
      FLASK_DEBUG: 1
      APP_SETTINGS: 'project.server.config.DevelopmentConfig'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    working_dir: /root/backend
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./backend:/root/backend
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    command: python3 -m gunicorn -c config.py wsgi:app
    depends_on:
      - db
      - file_server
    networks:
      - gait_anywhere_network

  db:
    image: mysql:8
    container_name: gait-anywhere-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 47002:3306
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      - gait_anywhere_network

  redis:
    image: redis:6-alpine
    container_name: gait-anywhere-redis
    networks:
      - gait_anywhere_network

  worker:
    image: gait-anywhere-backend:latest
    container_name: gait-anywhere-worker
    command: celery --app inference.tasks worker -P solo --loglevel=info --logfile=inference/logs/celery.log
    volumes:
      - ./backend:/root/backend
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    working_dir: /root/backend
    environment:
      <<: *common-variables
      FLASK_DEBUG: 1
      APP_SETTINGS: 'project.server.config.DevelopmentConfig'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
      CELERY_WORKER: gait-worker
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - frontend
      - backend
      - db
      - redis
      - file_server
    networks:
      - gait_anywhere_network

  file_server:
    image: gait-anywhere-file_server
    build:
      context: ./file_server/
      dockerfile: Dockerfile
    container_name: gait-anywhere-file_server
    ports:
      - 47003:5000
    stdin_open: true
    tty: true
    volumes:
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    working_dir: /data
    command: dufs -p 5000 --auth-method basic --auth ${SYNC_FILE_SERVER_USER}:${SYNC_FILE_SERVER_PASSWORD}@/:rw  -A .
    networks:
      - gait_anywhere_network

networks:
  gait_anywhere_network:
    name: gait_anywhere_network
