version: '3'

x-common-variables: &common-variables
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  CELERY_BACKEND_URL: 'redis://redis:6379/1'
  TASK_SYNC_URL: 'redis://redis:6379/2'
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
  BACKEND_FOLDER_PATH: ${PWD}/backend
  SYNC_FILE_SERVER_STORE_PATH: ${SYNC_FILE_SERVER_STORE_PATH}
  SYNC_FILE_SERVER_URL: 'http://file_server/'
  SYNC_FILE_SERVER_PORT: '5000'
  SYNC_FILE_SERVER_USER: ${SYNC_FILE_SERVER_USER}
  SYNC_FILE_SERVER_PASSWORD: ${SYNC_FILE_SERVER_PASSWORD}
  FOLDER_TO_STORE_TEMP_FILE_PATH: ${FOLDER_TO_STORE_TEMP_FILE_PATH}
  DOCKER_NETWORK: 'gait_anywhere_network'

x-dind-worker-settings: &common-dind-worker-settings
  image: gait-anywhere-backend:latest
  working_dir: /root/backend
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
  stdin_open: true
  tty: true
  volumes:
    - ${PWD}/backend:/root/backend
    - ${FOLDER_TO_STORE_TEMP_FILE_PATH}:/root/data
    - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
  networks:
    - gait_anywhere_network

services:
  frontend:
    build: 
      context: ./frontend/
      dockerfile: frontend.Dockerfile
    container_name: gait-anywhere-frontend
    ports:
      - 47000:80
    depends_on:
      - backend
      - file_server
    networks:
      - gait_anywhere_network

  backend:
    image: gait-anywhere-backend:latest
    build:
      context: ./backend/
      dockerfile: backend.Dockerfile
    container_name: gait-anywhere-backend
    environment:
      <<: *common-variables
      FLASK_DEBUG: 1
      APP_SETTINGS: 'project.server.config.DevelopmentConfig'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    working_dir: /root/backend
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./backend:/root/backend
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    command: python3 -m gunicorn -c config.py wsgi:app
    depends_on:
      - db
      - file_server
    networks:
      - gait_anywhere_network

  db:
    image: mysql:8
    container_name: gait-anywhere-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 47002:3306
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      - gait_anywhere_network

  redis:
    image: redis:6-alpine
    container_name: gait-anywhere-redis
    networks:
      - gait_anywhere_network

  main-worker:
    image: gait-anywhere-backend:latest
    container_name: gait-anywhere-main-worker
    command: celery --app inference.tasks worker -Q inference_gait_task_queue -n main-worker@%h -c 2 --without-heartbeat --loglevel=info --logfile=inference/logs/main-worker.log
    volumes:
      - ./backend:/root/backend
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    working_dir: /root/backend
    environment:
      <<: *common-variables
      FLASK_DEBUG: 1
      APP_SETTINGS: 'project.server.config.DevelopmentConfig'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
      CELERY_WORKER: gait-worker
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - frontend
      - backend
      - db
      - redis
      - file_server
    networks:
      - gait_anywhere_network

  file_server:
    image: gait-anywhere-file_server
    build:
      context: ./file_server/
      dockerfile: Dockerfile
    container_name: gait-anywhere-file_server
    ports:
      - 47003:5000
    stdin_open: true
    tty: true
    volumes:
      - ${SYNC_FILE_SERVER_STORE_PATH}:/data
    working_dir: /data
    command: dufs -p 5000 --auth-method basic --auth ${SYNC_FILE_SERVER_USER}:${SYNC_FILE_SERVER_PASSWORD}@/:rw  -A .
    networks:
      - gait_anywhere_network

  track_and_extract-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-track_and_extract-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.track_and_extract_task worker -Q track_and_extract_task_queue -n track_and_extract-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/track_and_extract-worker1.log

  turn_time-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-turn_time-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.turn_time_task worker -Q turn_time_task_queue -n turn_time-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/turn_time-worker1.log

  depth_estimation-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-depth_estimation-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.depth_estimation_task worker -Q depth_estimation_task_queue -n depth_estimation-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/depth_estimation-worker1.log

  video_generation-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-video_generation-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.video_generation_task worker -Q video_generation_task_queue -n video_generation-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/video_generation-worker1.log

  video_generation_3d-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-video_generation_3d-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.video_generation_3d_task worker -Q video_generation_3d_task_queue -n video_generation_3d-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/video_generation_3d-worker1.log

  svo_conversion-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-svo_conversion-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.svo_conversion_task worker -Q svo_conversion_task_queue -n svo_conversion-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/svo_conversion-worker1.log
  
  openpose-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-openpose-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.openpose_task worker -Q openpose_task_queue -n openpose-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/openpose-worker1.log

  svo_depth_sensing-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-svo_depth_sensing-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.svo_depth_sensing_task worker -Q svo_depth_sensing_task_queue -n svo_depth_sensing-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/svo_depth_sensing-worker1.log

  r_estimation-worker1:
    <<: *common-dind-worker-settings
    container_name: gait-anywhere-r_estimation-worker1
    environment:
      <<: *common-variables
      CELERY_WORKER: 'gait-worker'
      CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
      CUDA_VISIBLE_DEVICES: '0'
    command: celery --app algorithms.gait_basic.tasks.r_estimation_task worker -Q r_estimation_task_queue -n r_estimation-worker1@%h -c 1 --max-tasks-per-child=1 --without-heartbeat --loglevel=info --logfile=inference/logs/r_estimation-worker1.log

networks:
  gait_anywhere_network:
    name: gait_anywhere_network
